[package]
name = "functional"
version = "0.1.0"
authors = ["Yan Couto <yancouto@gmail.com>"]
edition = "2018"
default-run = "functional"

[features]
default = ["bracket-lib/opengl"]

curses = ["bracket-lib/curses"]

crossterm = ["bracket-lib/crossterm"]

[dependencies]
non-empty-vec = "0.1.2"
structopt = { version = "0.3", default-features = false }
lazy_static = "1.4.0"
jsonnet-rs = "0.17.0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }

[dependencies.bracket-lib]
version = "0.8.1"
default-features = false