[package]
name = "functional"
version = "0.1.0"
authors = ["Yan Couto <yancouto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.1"