[package]
name = "functional"
version = "0.1.0"
authors = ["Yan Couto <yancouto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bracket-lib/opengl"]

curses = ["bracket-lib/curses"]

crossterm = ["bracket-lib/crossterm"]

[dependencies]

[dependencies.bracket-lib]
version = "0.8.1"
default-features = false