(function() {var type_impls = {
"freetype_sys":[],
"glutin":[["<details class=\"toggle implementors-toggle\" open><summary><section id=\"impl-Formattable-for-u64\" class=\"impl\"><a class=\"src rightside\" href=\"src/winit/platform_impl/linux/x11/util/format.rs.html#53\">source</a><a href=\"#impl-Formattable-for-u64\" class=\"anchor\">§</a><h3 class=\"code-header\">impl <a class=\"trait\" href=\"glutin/platform/unix/x11/util/trait.Formattable.html\" title=\"trait glutin::platform::unix::x11::util::Formattable\">Formattable</a> for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u64.html\">u64</a></h3></section></summary><div class=\"impl-items\"><section id=\"associatedconstant.FORMAT\" class=\"associatedconstant trait-impl\"><a class=\"src rightside\" href=\"src/winit/platform_impl/linux/x11/util/format.rs.html#54\">source</a><a href=\"#associatedconstant.FORMAT\" class=\"anchor\">§</a><h4 class=\"code-header\">const <a href=\"glutin/platform/unix/x11/util/trait.Formattable.html#associatedconstant.FORMAT\" class=\"constant\">FORMAT</a>: <a class=\"enum\" href=\"glutin/platform/unix/x11/util/enum.Format.html\" title=\"enum glutin::platform::unix::x11::util::Format\">Format</a> = Format::Long</h4></section></div></details>","Formattable","glutin::platform::unix::x11::ffi::Atom","glutin::platform::unix::x11::ffi::Colormap","glutin::platform::unix::x11::ffi::Cursor","glutin::platform::unix::x11::ffi::Drawable","glutin::platform::unix::x11::ffi::Font","glutin::platform::unix::x11::ffi::GContext","glutin::platform::unix::x11::ffi::KeySym","glutin::platform::unix::x11::ffi::Mask","glutin::platform::unix::x11::ffi::Pixmap","glutin::platform::unix::x11::ffi::Time","glutin::platform::unix::x11::ffi::VisualID","glutin::platform::unix::x11::ffi::Window","glutin::platform::unix::x11::ffi::XID","glutin::platform::unix::x11::ffi::XIMFeedback","glutin::platform::unix::x11::ffi::RRCrtc","glutin::platform::unix::x11::ffi::RROutput","glutin::platform::unix::x11::ffi::RRMode","glutin::platform::unix::x11::ffi::RRProvider","glutin::platform::unix::x11::ffi::XRRModeFlags","glutin::platform::unix::x11::ffi::Glyph","glutin::platform::unix::x11::ffi::GlyphSet","glutin::platform::unix::x11::ffi::PictFormat","glutin::platform::unix::x11::ffi::Picture"]],
"glutin_egl_sys":[],
"glutin_glx_sys":[],
"nix":[],
"serde":[],
"winit":[],
"x11_dl":[],
"xi_rope":[]
};if (window.register_type_impls) {window.register_type_impls(type_impls);} else {window.pending_type_impls = type_impls;}})()