(function() {var type_impls = {
"freetype_sys":[],
"glutin":[["<details class=\"toggle implementors-toggle\" open><summary><section id=\"impl-Pixel-for-u32\" class=\"impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#124\">source</a><a href=\"#impl-Pixel-for-u32\" class=\"anchor\">§</a><h3 class=\"code-header\">impl <a class=\"trait\" href=\"glutin/dpi/trait.Pixel.html\" title=\"trait glutin::dpi::Pixel\">Pixel</a> for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a></h3></section></summary><div class=\"impl-items\"><section id=\"method.from_f64\" class=\"method trait-impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#125\">source</a><a href=\"#method.from_f64\" class=\"anchor\">§</a><h4 class=\"code-header\">fn <a href=\"glutin/dpi/trait.Pixel.html#tymethod.from_f64\" class=\"fn\">from_f64</a>(f: <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f64.html\">f64</a>) -&gt; <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a></h4></section><section id=\"method.cast\" class=\"method trait-impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#109\">source</a><a href=\"#method.cast\" class=\"anchor\">§</a><h4 class=\"code-header\">fn <a href=\"glutin/dpi/trait.Pixel.html#method.cast\" class=\"fn\">cast</a>&lt;P&gt;(self) -&gt; P<div class=\"where\">where\n    P: <a class=\"trait\" href=\"glutin/dpi/trait.Pixel.html\" title=\"trait glutin::dpi::Pixel\">Pixel</a>,</div></h4></section></div></details>","Pixel","glutin::platform::unix::x11::ffi::XcursorDim","glutin::platform::unix::x11::ffi::XcursorPixel","glutin::platform::unix::x11::ffi::XcursorUInt","glutin::platform::unix::x11::ffi::BarrierEventID","glutin::event::ScanCode","glutin::event::AxisId","glutin::event::ButtonId"]],
"glutin_egl_sys":[],
"glutin_glx_sys":[],
"nix":[],
"serde":[],
"winit":[["<details class=\"toggle implementors-toggle\" open><summary><section id=\"impl-Pixel-for-u32\" class=\"impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#124-128\">source</a><a href=\"#impl-Pixel-for-u32\" class=\"anchor\">§</a><h3 class=\"code-header\">impl <a class=\"trait\" href=\"winit/dpi/trait.Pixel.html\" title=\"trait winit::dpi::Pixel\">Pixel</a> for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a></h3></section></summary><div class=\"impl-items\"><section id=\"method.from_f64\" class=\"method trait-impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#125-127\">source</a><a href=\"#method.from_f64\" class=\"anchor\">§</a><h4 class=\"code-header\">fn <a href=\"winit/dpi/trait.Pixel.html#tymethod.from_f64\" class=\"fn\">from_f64</a>(f: <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f64.html\">f64</a>) -&gt; Self</h4></section><section id=\"method.cast\" class=\"method trait-impl\"><a class=\"src rightside\" href=\"src/winit/dpi.rs.html#109-111\">source</a><a href=\"#method.cast\" class=\"anchor\">§</a><h4 class=\"code-header\">fn <a href=\"winit/dpi/trait.Pixel.html#method.cast\" class=\"fn\">cast</a>&lt;P: <a class=\"trait\" href=\"winit/dpi/trait.Pixel.html\" title=\"trait winit::dpi::Pixel\">Pixel</a>&gt;(self) -&gt; P</h4></section></div></details>","Pixel","winit::event::ScanCode","winit::event::AxisId","winit::event::ButtonId"]],
"x11_dl":[]
};if (window.register_type_impls) {window.register_type_impls(type_impls);} else {window.pending_type_impls = type_impls;}})()