name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - name: Install linux dependencies
      run: sudo apt-get install libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libopenal-dev libsndfile1-dev
    - name: Check format
      run: cargo fmt -- --verbose --check
    - name: Build
      run: cargo build --verbose --no-default-features --features bracket-lib/opengl
    - name: Run tests
      run: cargo test --verbose --no-default-features --features bracket-lib/opengl
    - name: Build docs
      run: cargo doc --verbose --no-default-features --features bracket-lib/opengl
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: target/doc
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
