name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - name: Install linux dependencies
      run: sudo apt-get install xorg-dev
    - name: Check format
      run: cargo fmt -- --verbose --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
